[[social]]
icon = "fa-classic fa-envelope"
url = "mailto:info@thismachinemodular.co.uk"
[[social]]
icon = "fa-brands fa-instagram"
url = "https://www.instagram.com/thismachinemodular"
[[social]]
icon = "fa-brands fa-youtube"
url = "https://www.youtube.com/@ThisMachineModular"