[[contact]]
name = "Instagram"
address = "https://www.instagram.com/thismachinemodular"
icon = "fa-instagram"
[[contact]]
name = "Email"
address = """<a href="info@thismachinemodular.co.uk">info@thismachinemodular.co.uk</a>"""
icon = "fa-envelope"
[[contact]]
name = "Address"
address = "Sheffield UK"
icon = "fa-map-marked-alt"
[[social]]
icon = "fa-instagram"
url = "https://www.instagram.com/thismachinemodular"
[[social]]
icon = "fa-youtube"
url = "https://www.youtube.com/@ThisMachineModular"